# Uncomment the next line to define a global platform for your project


#platform :ios, '9.0'

target 'ViewAnimator2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
   #pod 'ViewAnimato-iOS', :podspec => '/Users/gulshan/ViewAnimator-iOS/'


  # Pods for ViewAnimator2

  target 'ViewAnimator2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViewAnimator2UITests' do
    # Pods for testing
  end

end
